# Generated by Django 3.2.4 on 2021-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('item_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('shop', models.CharField(max_length=20)),
            ],
        ),
    ]
